version: '2'
volumes:
  nvidia_driver_384.90:
    external: true
  nfs:
    driver: rancher-nfs

services:
  tf:
    image: gcr.io/tensorflow/tensorflow:latest-gpu
    environment:
      PASSWORD: $PASSWD
    devices:
    - /dev/nvidia0:/dev/nvidia0:rwm
    - /dev/nvidia1:/dev/nvidia1:rwm
    - /dev/nvidia1:/dev/nvidia2:rwm
    - /dev/nvidia1:/dev/nvidia3:rwm
    - /dev/nvidiactl:/dev/nvidiactl:rwm
    - /dev/nvidia-uvm:/dev/nvidia-uvm:rwm
    - /dev/nvidia-uvm-tools:/dev/nvidia-uvm-tools:rwm
    volumes:
    - nvidia_driver_384.90:/usr/local/nvidia:ro
    - nfs:/notebooks
    ports:
    - 8888/tcp