version: '2'
services:
  repo:
    image: anujkhanna/cookiecutter-python-data-science
    entrypoint: [source, env-secrets.sh]
    environment:
      FULL_NAME: $FULL_NAME
      EMAIL: $EMAIL
      GITLAB_URL: $GITLAB_URL
      PROJECT_NAME: $PROJECT_NAME
      GROUP_NAME: $NAME_SPACE
      PROJECT_SHORT_DESCRIPTION: $PROJECT_SHORT_DESCRIPTION
      GITLAB_PERSONAL_TOKEN: $GITLAB_PERSONAL_TOKEN
    labels:
      io.rancher.container.pull_image: always
    ports:
    - 8888/tcp